apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.configMap.name }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
data:
    {{- range $key, $val := .Values.configMapValues }}
    {{ $key | quote }}: {{ $val | quote }}
    {{- end}}